# -*- coding: utf-8 -*-
"""functions.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Om9y8r4D4VVrj8ZjkQEId2yg7-mUSwSA
"""

def add(a,b):
  return a + b


def multiple(a,b):
  return 10 * a * b
